### PR TITLE
Remove box around legend in mpl plot

### PR DESCRIPTION
**Pull request by e-koch**
The markers in the png output were overlapping with the box. I just removed the box so it's cleaner and looks slightly more like the html plot.

### CODE REVIEW

**Comment by e-koch** [comment]
image

**Comment by e-koch** [comment]
Perhaps they should be more spread out too?

**Comment by jmdkastro** [comment]
Looks good! To answer your question:
Vertically: no
Symbols horizontally: maybe yes

**Comment by e-koch** [comment]
image

**Comment by jmdkastro** [comment]
Merge! :-)

**Pull request merged**
