### PR TITLE
Marker sizes, Plot Extents

### PR DESCRIPTION
**Pull request by e-koch**
WIP -- A couple other things need to be added before merging in.

Addresses second point in #101 and #48.

### CODE REVIEW

**Comment by e-koch** [comment]
surfacedensity_velocitydispersion_radiustest
surfacedensity_velocitydispersion_radiustest
surfacedensity_velocitydispersion_radiustest

**Comment by keflavich** [comment]
looks plotty good.  mergeable? mergible?  mergable?  spellcheck says these are all wrong.  the first is correct.  We'll go with zusammenführbar from now on

**Comment by e-koch** [comment]
In the plots above, I altered the zMax (largest radius which would be from the query form). Ignore the labels on the axes, that was just a local problem and isn't changed in the code.

Changes:
- The marker sizes now scale based on the max and min of the data (not zMin and zMax). The plotting routine accepts a pixel limit for the smallest and largest markers, and scales the data between these. The pixel limit can be set to the number of pixels are a fraction of the pixels along the smallest axis (fraction between 0 and 1).
- The representative sizes in the upper corner now scale based on the data to be plotted. It plots a max of 3 points rounded to the nearest powers of 10. If the range is ~1 dex, no middle point is plotted.
- The limits are now padded by the largest marker width, so points can't be partially cutoff.

**Comment by e-koch** [comment]
@keflavich Yup! Mergibility confirmed.

**Comment by e-koch** [comment]
@keflavich -- Actually one sec.

**Comment by e-koch** [comment]
@keflavich - Good now! The hacked in labels were still in there.

**Comment by jmdkastro** [comment]
@e-koch @keflavich 
Sorry for being late to the party: maybe it's a good idea to have the legend symbols be separated by 1-dex intervals always? So let the number of legend symbols depend on the dynamic range of the data? I think the 0.1 -- 1 -- 100 pc example looks a bit confusing. Given the limited dynamic range available in the universe, I don't expect more than five symbols ever (anyone who isn't outputting the entire database won't be comparing entire galaxies to cores, so it'll usually be much less).

**Pull request merged**
